pool:
  vmImage: ubuntu-latest

trigger: none

steps:
  - task: DotNetCoreCLI@2
    displayName: Clean
    inputs:
      command: 'clean'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2  
    displayName: Build All Projects
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release --no-restore'
      continueOnError: true

  - task: DotNetCoreCLI@2  
    displayName: Test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      publishTestResults: true
      testResultsFiles: '**/TestResults/*.xml'
      continueOnError: true

  - task: DotNetCoreCLI@2  
    displayName: Publish
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      continueOnError: true

  - task: PublishBuildArtifacts@1  
    displayName: Publish Artifact
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      continueOnError: true
